### ISSUE TITLE
Add retry for doc-store retrieval failures

### ISSUE THREAD

**Issue by PSeitz** [quickwit-inc/quickwit#409] opened 2021-08-17 08:04 UTC
Follow-up to https://github.com/quickwit-inc/quickwit/issues/124, which handles retry for search, but not if a node becomes unreachable between search and doc store retrieval.

**Comment by fmassot** [comment] 2021-09-01 10:42
@PSeitz this is a duplicate of #380, closing this one but feel free to reopen it if you think it's still usefule.

**Closed by fmassot** 2021-09-01 10:42 UTC
Labels: enhancement
