### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by brycefisher** [quickwit-inc/quickwit#828] opened 2021-12-01 21:43 UTC
**Is your feature request related to a problem? Please describe.**
I'd love to replace ES / Kibana with quickwit, but I don't know how I could quickly and efficiently search through applications to resolve a production incident.

**Describe the solution you'd like**
Ideally, I'd like a minimal kibana replacement: a search box and time picker with results shown below. Result items could be expanded.

**Describe alternatives you've considered**
 * Just trying to use a cli to craft queries in the terminal
 * Making an "adapter" so kibana could be pointed at a quickwit instance for a subset of functionality (even to search documents and examine documents, but probably not admin indices etc)

**Additional context**
I _think_ that y'all have the opportunity to disrupt application logs space with your model of S3 as the data store, especially for small scale hobby projects.

**Comment by brycefisher** [comment] 2021-12-03 22:20
See also the `zinc` project which has similar goals but no S3 storage and does include a UI: https://github.com/prabhatsharma/zinc/issues/2

**Comment by fmassot** [comment] 2021-12-03 22:34
Thanks, @brycefisher for your detailed issue.

A few months ago, we made a UI for our POC and it has the search box and a date picker :) 
For us, it's too early to embed such a UI into this repository but I think we can open-source it as a separate project. Would it be useful for your needs?

**Comment by brycefisher** [comment] 2021-12-04 19:51
Very!! So excited to hear this.

**Comment by fulmicoton** [comment] 2022-01-13 04:13
@brycefisher FYI This feature is scheduled for quickwit 0.3.

**Comment by fmassot** [comment] 2022-01-16 21:54
Closing as this is a duplicate of #155

**Closed by fmassot** 2022-01-16 21:54 UTC
Labels: enhancement
